// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtGA-N-QgQND-CBSAjWtz-qJ5OsKJjtew',
    appId: '1:259036034618:web:6ff24bbc9eb3409da0e703',
    messagingSenderId: '259036034618',
    projectId: 'ln-lo-reg-tst-strg-fires-a9089',
    authDomain: 'ln-lo-reg-tst-strg-fires-a9089.firebaseapp.com',
    storageBucket: 'ln-lo-reg-tst-strg-fires-a9089.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYYDWhKqU3nPLl_t2-hGFuBqn-QSzV8Ng',
    appId: '1:259036034618:android:5fb0c22c18f6fc0aa0e703',
    messagingSenderId: '259036034618',
    projectId: 'ln-lo-reg-tst-strg-fires-a9089',
    storageBucket: 'ln-lo-reg-tst-strg-fires-a9089.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVzDJWgS5zVu3eFnTP7CSjN-7LLAGTu78',
    appId: '1:259036034618:ios:9a64ed8cd78325dfa0e703',
    messagingSenderId: '259036034618',
    projectId: 'ln-lo-reg-tst-strg-fires-a9089',
    storageBucket: 'ln-lo-reg-tst-strg-fires-a9089.firebasestorage.app',
    iosBundleId: 'com.example.practiceFlutterApplication38',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtGA-N-QgQND-CBSAjWtz-qJ5OsKJjtew',
    appId: '1:259036034618:web:53474118ccdee859a0e703',
    messagingSenderId: '259036034618',
    projectId: 'ln-lo-reg-tst-strg-fires-a9089',
    authDomain: 'ln-lo-reg-tst-strg-fires-a9089.firebaseapp.com',
    storageBucket: 'ln-lo-reg-tst-strg-fires-a9089.firebasestorage.app',
  );

}